### ISSUE TITLE
X Error of failed request:  BadAccess

### ISSUE THREAD

**Issue by ghuter** [LoupLobet/91menu#4]
Hi,

I recently tried the program and I'm getting this error:

    X Error of failed request:  BadAccess (attempt to access private resource denied)
      Major opcode of failed request:  28 (X_GrabButton)
      Serial number of failed request:  50
      Current serial number in output stream:  52

don't know why, am I doing things wrongly?

If this problem inpires you, please tell me if you need any more information

**Comment by LoupLobet** [comment]
Hi,

Of course ! I'll try my best to solve your problem.
Can you give me the command that generate this output ? Plus your config.h.
Have you made any modifications in the code, or is it a vanilla build ?

**Comment by LoupLobet** [comment]
It seems that it's the XGrabButton(3) function that create the error. I think it's because it grabs mouse buttons in the root window (and 91menu seems to don't have enough permissions). Do you have any kind of hardened X environement (don't really know if this kind of thing exists).

I've found this in the Xlib manual : "If some other client has already issued a XGrabButton() with the same button/key combination on the same window, a BadAccess error results. When using AnyModifier or AnyButton, the request fails completely, and a BadAccess error results (no grabs are established) if there is a conflicting grab for any combination. XGrabButton() has no effect on an active grab."

I'm looking for a solution ...

**Comment by LoupLobet** [comment]
I just commit a kind of fixe, I don't know if it will do the trick (I don't have the problem, so can't see if it solve anything). Please pull, remake, reinstall, and tell me I the problem persists :)

**Comment by ghuter** [comment]
I just modified the Makefile, because the original one was doing an error for me:
it couldn't find utf8.o and util.o

Here is the diff:
```
diff --git a/Makefile b/Makefile
index daa5721..28ccf76 100644
--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@ CPPFLAGS = -DVERSION=\"${VERSION}\" -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOU
 CFLAGS = -std=c99 -pedantic -Wall -Os ${CPPFLAGS} ${INCS}
 LDFLAGS = ${LIBS}
 
-all: clean options 91menu clean_object
+all: 91menu
 
 options:
 	@echo 91menu build options:
@@ -36,7 +36,7 @@ config.h:
 .c.o :
 	${CC} -c ${CFLAGS} $<
 
-91menu: 91menu.o drw.o utf8.o util.o
+91menu: options 91menu.o drw.o utf8.o util.o
 	${CC} -o $@ 91menu.o drw.o utf8.o util.o ${LDFLAGS}
 
 clean_object:
@@ -45,7 +45,7 @@ clean:
 	rm -f 91menu 91menu.o drw.o utf8.o util.o *.core
 	[ -e config.h ] || cp config.def.h config.h
 
-install: all
+install: 91menu
 	mkdir -p ${DESTDIR}${PREFIX}/bin
 	cp -r 91menu ${DESTDIR}${PREFIX}/bin
 	chmod 755 ${DESTDIR}${PREFIX}/bin/91menu
```

Otherwise, after pulling and remaking, it seems to work just fine now. Thanks!

**Comment by LoupLobet** [comment]
Ok super nice ! I close the issue. If you have any other problems/questions, don't hesitate ;) !
