### ISSUE TITLE
Click and Release behavior on Tiling Window Managers

### ISSUE THREAD

**Issue by glemborg** [LoupLobet/91menu#5]
Is there a way to make 91menu respond on root window events when mouse3 click was used to invoke 91menu itself?

91menu ButtonRelease event works when lauched from the terminal like on rio. 

It seems this behavior is not limited to 91menu though, it also happens with xmenu on different window managers as well. For reference, I am using DWM with `ClkRootWin` to call 91menu.

Thank you,
glemborg

**Comment by LoupLobet** [comment]
Sadly I never managed to make it work (if it's possible). The thing is, the mouse pressed event is catched by dwm (ClkRootWin triggering), and 91menu can't catch the mouse release without a mouse pressed event.
The only solution I found to have this kind of interaction, is to build the menu in the window manager itself (same way rio does), to catch the mouse pressed and the mouse release event with the same X11 event loop. But it doesn't make any sens since the goal of 91menu is to bring a rio like menu to other environments regardless of the windowmanager you choose.
